#
# File: Makefile
#
# Copyright 2009 TiVo Inc. All Rights Reserved.
#
###############################################################################

# See the e2fsprogs-1.41.4-release/Makefile for more information.

ISM_DEPTH=.
include $(ISM_DEPTH)/ismdefs

DIRS = ${E2FSPROGS_RELEASE}

include $(COMMONRULES)
