#
# File: Makefile
#
# Copyright 2010 TiVo Inc. All Rights Reserved.
#
###############################################################################

ISM_DEPTH	:= ./../../..
include $(ISM_DEPTH)/ismdefs

SFILES := \
	ctype-compat.c \
	$(NULL)

SHLIBS := $(ISM_LIBDIR)/libglibctivocompat.so

default:

include $(ISMRULES)
