/***************************************************************************
 *     Copyright (c) 1999-2009, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: bchp_uartb.h $
 * $brcm_Revision: Hydra_Software_Devel/1 $
 * $brcm_Date: 1/29/09 11:04p $
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on         Thu Jan 29 15:30:20 2009
 *                 MD5 Checksum         0a9f974b7551a1ff1e1f6c0bddfbd2ab
 *
 * Compiled with:  RDB Utility          combo_header.pl
 *                 RDB Parser           3.0
 *                 unknown              unknown
 *                 Perl Interpreter     5.008008
 *                 Operating System     linux
 *
 * Revision History:
 *
 * $brcm_Log: /magnum/basemodules/chp/7405/rdb/d0/bchp_uartb.h $
 * 
 * Hydra_Software_Devel/1   1/29/09 11:04p albertl
 * PR51716: Initial revision.
 *
 ***************************************************************************/

#ifndef BCHP_UARTB_H__
#define BCHP_UARTB_H__

/***************************************************************************
 *UARTB - UART B
 ***************************************************************************/
#define BCHP_UARTB_RBR                           0x00400b40 /* Receive Buffer Register */
#define BCHP_UARTB_THR                           0x00400b40 /* Transmit Holding Register */
#define BCHP_UARTB_DLH                           0x00400b44 /* Divisor Latch High */
#define BCHP_UARTB_DLL                           0x00400b40 /* Divisor Latch Low */
#define BCHP_UARTB_IER                           0x00400b44 /* Interrupt Enable Register */
#define BCHP_UARTB_IIR                           0x00400b48 /* Interrupt Identity Register */
#define BCHP_UARTB_FCR                           0x00400b48 /* FIFO Control Register */
#define BCHP_UARTB_LCR                           0x00400b4c /* Line Control Register */
#define BCHP_UARTB_MCR                           0x00400b50 /* Modem Control Register */
#define BCHP_UARTB_LSR                           0x00400b54 /* Line Status Register */
#define BCHP_UARTB_MSR                           0x00400b58 /* Modem Status Register */
#define BCHP_UARTB_SCR                           0x00400b5c /* Scratchpad Register */

#endif /* #ifndef BCHP_UARTB_H__ */

/* End of File */
