#
# File: Makefile
#
# Copyright 2010 TiVo Inc. All Rights Reserved.
#
###############################################################################

ISM_DEPTH=.
include $(ISM_DEPTH)/ismdefs

ifeq ($(BOOTARCH),mips)
DIRS = common/lib/glibctivocompat
endif

include $(COMMONRULES)
