#
# File: Makefile
#
# Copyright (c) 2009 TiVo Inc.
#
###############################################################################


ISM_DEPTH := ./..
include $(ISM_DEPTH)/ismdefs

DIRS= libavcodec libavformat libavdevice libavutil libswscale

include $(COMMONRULES)
